### ISSUE TITLE
Command History rows do not update until subsequent row received

### ISSUE THREAD

**Issue by akhenry** [akhenry/openmct-yamcs#405] opened 2024-01-03 17:50 UTC
Originally reported as VIPERGC-320

#### Summary
An issue was reported with the command history capability in Open MCT whereby a new command would only appear once a subsequent command was received.

For context, the handling of Commands in Open MCT is different to other types of telemetry. A single command in Yamcs goes through multiple states, each of which is separately emitted to Open MCT. Open MCT collates all of these state changes into a single row.

#### Expected vs Current Behavior
Command history rows should appear in the command history table immediately upon receipt.

#### Impact Check List
- [x] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Environment
* Open MCT Version: Unknown
* Deployment Type: MMOC

**Comment by ozyx** [comment] 2024-02-07 23:56
I'm having trouble reproducing this locally w/ quickstart and also on Testathon.

**Comment by scottbell** [comment] 2024-02-14 18:16
Not sure if this is related:
https://github.com/akhenry/openmct-yamcs/issues/384

**Comment by ozyx** [comment] 2024-02-20 18:14
Marking as retest for 4.0.0

**Closed** 2024-03-18 20:44 UTC
Labels: type:bug, severity:critical, bug:retest

**Comment by ozyx** [comment] 2024-03-19 21:44
Tested this again, cannot reproduce. This is fixed
